- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: OPS!
      debug:
        msg: "OPS!"
      failed_when: inventory_hostname == 'localhost'
